-- Reference SQL for migration 0009; run vnfest-migrate --apply.
-- The executable Go migration contains the complete SQLite schema and all
-- compatibility indexes. These compact declarations document the tables that
-- are added without requiring a CGO/SQLite command-line tool on Windows.
CREATE TABLE IF NOT EXISTS recognition_programs (id INTEGER PRIMARY KEY AUTOINCREMENT, club_id INTEGER NOT NULL, country TEXT NOT NULL DEFAULT 'china', type TEXT NOT NULL DEFAULT 'assessment', title TEXT NOT NULL, intro TEXT, status TEXT NOT NULL DEFAULT 'draft', capabilities TEXT NOT NULL, created_by INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_program_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, program_id INTEGER NOT NULL, version_no TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', content_snapshot TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(program_id,version_no));
CREATE TABLE IF NOT EXISTS recognition_badges (id INTEGER PRIMARY KEY AUTOINCREMENT, club_id INTEGER NOT NULL, country TEXT NOT NULL DEFAULT 'china', name TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'participation', image_url TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, created_by INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_connectors (id INTEGER PRIMARY KEY AUTOINCREMENT, club_id INTEGER NOT NULL, country TEXT NOT NULL DEFAULT 'china', name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'webhook', token_prefix TEXT NOT NULL, token_hash TEXT NOT NULL, hmac_secret TEXT NOT NULL DEFAULT '', scope TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', created_by INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_events (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL UNIQUE, idempotency_key TEXT NOT NULL DEFAULT '' UNIQUE, schema_version TEXT NOT NULL DEFAULT '1.0', type TEXT NOT NULL, occurred_at TEXT NOT NULL, data TEXT, status TEXT NOT NULL DEFAULT 'processed', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, program_version_id INTEGER NOT NULL, user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'created', score INTEGER, answers TEXT, attempt_no INTEGER NOT NULL DEFAULT 1, started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at TEXT, UNIQUE(program_version_id,user_id,attempt_no));
CREATE TABLE IF NOT EXISTS recognition_submissions (id INTEGER PRIMARY KEY AUTOINCREMENT, program_version_id INTEGER NOT NULL, user_id INTEGER NOT NULL, content TEXT, file_path TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', reviewed_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, submission_id INTEGER NOT NULL, reviewer_id INTEGER NOT NULL, decision TEXT NOT NULL, comment TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(submission_id,reviewer_id));
CREATE TABLE IF NOT EXISTS recognition_credentials (id INTEGER PRIMARY KEY AUTOINCREMENT, credential_uid TEXT NOT NULL UNIQUE, holder_user_id INTEGER NOT NULL, badge_id INTEGER NOT NULL, program_id INTEGER NOT NULL, program_version_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active', issued_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at TEXT, revoked_at TEXT);
CREATE TABLE IF NOT EXISTS recognition_outbox (id INTEGER PRIMARY KEY AUTOINCREMENT, task_type TEXT NOT NULL, payload TEXT, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at TEXT);
CREATE TABLE IF NOT EXISTS recognition_identity_links (id INTEGER PRIMARY KEY AUTOINCREMENT, external_provider TEXT NOT NULL, external_subject_id TEXT NOT NULL, vnfmap_user_id INTEGER, verification_status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(external_provider,external_subject_id));
CREATE TABLE IF NOT EXISTS recognition_claim_codes (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, program_id INTEGER NOT NULL, program_version_id INTEGER NOT NULL, badge_id INTEGER NOT NULL, redeemed_by INTEGER, redeemed_at TEXT, expires_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_club_roles (id INTEGER PRIMARY KEY AUTOINCREMENT, club_id INTEGER NOT NULL, country TEXT NOT NULL DEFAULT 'china', user_id INTEGER NOT NULL, role TEXT NOT NULL, granted_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(club_id,country,user_id,role));
