-- Reference SQL for migration 0009; run vnfest-migrate, not this file directly.
CREATE TABLE IF NOT EXISTS recognition_programs (id INT PRIMARY KEY AUTO_INCREMENT, club_id INT NOT NULL, country VARCHAR(50) NOT NULL DEFAULT 'china', type VARCHAR(30) NOT NULL DEFAULT 'assessment', title VARCHAR(255) NOT NULL, intro TEXT, participant_difficulty VARCHAR(20) NOT NULL DEFAULT 'normal', visibility VARCHAR(20) NOT NULL DEFAULT 'public', status VARCHAR(20) NOT NULL DEFAULT 'draft', capabilities TEXT NOT NULL, participation_rules TEXT, max_attempts INT NOT NULL DEFAULT 0, cooldown_minutes INT NOT NULL DEFAULT 0, open_at DATETIME NULL, close_at DATETIME NULL, max_issuance INT NOT NULL DEFAULT 0, credential_ttl_days INT NOT NULL DEFAULT 0, security_level VARCHAR(20) NOT NULL DEFAULT 'normal', created_by INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_program_versions (id INT PRIMARY KEY AUTO_INCREMENT, program_id INT NOT NULL, version_no VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', content_snapshot MEDIUMTEXT NOT NULL, published_by INT NULL, published_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_recog_ver (program_id,version_no));
CREATE TABLE IF NOT EXISTS recognition_badges (id INT PRIMARY KEY AUTO_INCREMENT, club_id INT NOT NULL, country VARCHAR(50) NOT NULL DEFAULT 'china', name VARCHAR(255) NOT NULL, category VARCHAR(30) NOT NULL DEFAULT 'participation', description TEXT, image_url VARCHAR(500) NOT NULL DEFAULT '', version INT NOT NULL DEFAULT 1, created_by INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_connectors (id INT PRIMARY KEY AUTO_INCREMENT, club_id INT NOT NULL, country VARCHAR(50) NOT NULL DEFAULT 'china', name VARCHAR(128) NOT NULL, type VARCHAR(40) NOT NULL DEFAULT 'webhook', token_prefix VARCHAR(16) NOT NULL, token_hash VARCHAR(128) NOT NULL, hmac_secret VARCHAR(255) NOT NULL DEFAULT '', scope TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_by INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, last_used_at DATETIME NULL, revoked_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS recognition_events (id INT PRIMARY KEY AUTO_INCREMENT, event_id VARCHAR(64) NOT NULL UNIQUE, idempotency_key VARCHAR(128) NOT NULL DEFAULT '', schema_version VARCHAR(10) NOT NULL DEFAULT '1.0', type VARCHAR(128) NOT NULL, club_id INT NULL, country VARCHAR(50) NOT NULL DEFAULT 'china', user_id INT NULL, program_id INT NULL, program_version_id INT NULL, badge_id INT NULL, connector_id INT NULL, occurred_at DATETIME NOT NULL, data TEXT, evidence_refs TEXT, source_verified TINYINT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'processed', error_message VARCHAR(500) NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_recog_evt_idem (idempotency_key));
CREATE TABLE IF NOT EXISTS recognition_attempts (id INT PRIMARY KEY AUTO_INCREMENT, program_version_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'created', score INT NULL, answers MEDIUMTEXT, attempt_no INT NOT NULL DEFAULT 1, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at DATETIME NULL, UNIQUE KEY uq_recog_att_sess (program_version_id,user_id,attempt_no));
CREATE TABLE IF NOT EXISTS recognition_submissions (id INT PRIMARY KEY AUTO_INCREMENT, program_version_id INT NOT NULL, user_id INT NOT NULL, content TEXT, file_path VARCHAR(500) NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'pending', reviewed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_reviews (id INT PRIMARY KEY AUTO_INCREMENT, submission_id INT NOT NULL, reviewer_id INT NOT NULL, decision VARCHAR(20) NOT NULL, comment TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_recog_rev (submission_id,reviewer_id));
CREATE TABLE IF NOT EXISTS recognition_credentials (id INT PRIMARY KEY AUTO_INCREMENT, credential_uid VARCHAR(64) NOT NULL UNIQUE, holder_user_id INT NOT NULL, badge_id INT NOT NULL, badge_version INT NOT NULL DEFAULT 1, issuer_club_id INT NOT NULL, issuer_country VARCHAR(50) NOT NULL DEFAULT 'china', program_id INT NOT NULL, program_version_id INT NOT NULL, credential_type VARCHAR(30) NOT NULL DEFAULT 'participation', verification_level VARCHAR(30) NOT NULL DEFAULT 'auto', status VARCHAR(20) NOT NULL DEFAULT 'active', condition_snapshot TEXT, evidence_refs TEXT, public_visibility TINYINT NOT NULL DEFAULT 1, issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NULL, revocation_reason VARCHAR(255) NULL, revoked_at DATETIME NULL, revoked_by INT NULL, superseded_by INT NULL);
CREATE TABLE IF NOT EXISTS recognition_outbox (id INT PRIMARY KEY AUTO_INCREMENT, task_type VARCHAR(40) NOT NULL, payload TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(500) NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS recognition_identity_links (id INT PRIMARY KEY AUTO_INCREMENT, external_provider VARCHAR(40) NOT NULL, external_subject_id VARCHAR(191) NOT NULL, vnfmap_user_id INT NULL, verification_status VARCHAR(20) NOT NULL DEFAULT 'pending', linked_at DATETIME NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_recog_idl_active (external_provider,external_subject_id));
CREATE TABLE IF NOT EXISTS recognition_claim_codes (id INT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(32) NOT NULL UNIQUE, program_id INT NOT NULL, program_version_id INT NOT NULL, badge_id INT NOT NULL, redeemed_by INT NULL, redeemed_at DATETIME NULL, expires_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS recognition_club_roles (id INT PRIMARY KEY AUTO_INCREMENT, club_id INT NOT NULL, country VARCHAR(50) NOT NULL DEFAULT 'china', user_id INT NOT NULL, role VARCHAR(30) NOT NULL, granted_by INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_recog_role (club_id,country,user_id,role));
