-- Reference SQL for migration 0010; vnfest-migrate --apply is authoritative.
CREATE TABLE IF NOT EXISTS vote_projects (id INTEGER PRIMARY KEY AUTOINCREMENT, project_type TEXT NOT NULL, club_id INTEGER NOT NULL, country TEXT NOT NULL DEFAULT 'china', title TEXT NOT NULL, year_label TEXT NOT NULL DEFAULT '', description TEXT, cover_url TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'draft', visibility TEXT NOT NULL DEFAULT 'public', eligibility_mode TEXT NOT NULL DEFAULT 'club_member', result_visibility TEXT NOT NULL DEFAULT 'after_stage', config_json TEXT, share_token TEXT NOT NULL DEFAULT '', guest_vote INTEGER NOT NULL DEFAULT 0, created_by INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, published_at TEXT, ended_at TEXT);
CREATE TABLE IF NOT EXISTS vote_stages (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, stage_key TEXT NOT NULL, title TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 1, stage_type TEXT NOT NULL, vote_mode TEXT NOT NULL DEFAULT 'multi_select', max_select INTEGER NOT NULL DEFAULT 1, advance_count INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'draft', starts_at TEXT, ends_at TEXT, config_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(project_id,stage_key));
CREATE TABLE IF NOT EXISTS vote_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, source_type TEXT NOT NULL DEFAULT 'manual', source_id TEXT NOT NULL DEFAULT '', identity_key TEXT NOT NULL, title TEXT NOT NULL, title_cn TEXT NOT NULL DEFAULT '', subtitle TEXT NOT NULL DEFAULT '', image_url TEXT NOT NULL DEFAULT '', summary TEXT, external_url TEXT NOT NULL DEFAULT '', entry_status TEXT NOT NULL DEFAULT 'pending', submitted_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(project_id,identity_key));
CREATE TABLE IF NOT EXISTS vote_nominations (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, entry_id INTEGER NOT NULL, user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(project_id,entry_id,user_id));
CREATE TABLE IF NOT EXISTS vote_votes (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, stage_id INTEGER NOT NULL, entry_id INTEGER NOT NULL, user_id INTEGER, guest_key TEXT NOT NULL DEFAULT '', score INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(stage_id,entry_id,user_id,guest_key));
CREATE TABLE IF NOT EXISTS vote_stage_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, stage_id INTEGER NOT NULL, entry_id INTEGER NOT NULL, group_key TEXT NOT NULL DEFAULT '', seed_no INTEGER NOT NULL DEFAULT 0, source_stage_id INTEGER, source_result_rank INTEGER, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(stage_id,entry_id));
CREATE TABLE IF NOT EXISTS vote_matches (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, stage_id INTEGER NOT NULL, round_no INTEGER NOT NULL DEFAULT 1, match_no INTEGER NOT NULL DEFAULT 1, slot_a_entry_id INTEGER, slot_b_entry_id INTEGER, winner_entry_id INTEGER, status TEXT NOT NULL DEFAULT 'pending', next_match_id INTEGER, next_slot TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vote_results (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id INTEGER NOT NULL, stage_id INTEGER NOT NULL, entry_id INTEGER NOT NULL, rank_no INTEGER NOT NULL DEFAULT 0, votes INTEGER NOT NULL DEFAULT 0, score_avg REAL, advanced INTEGER NOT NULL DEFAULT 0, snapshot_json TEXT, settled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(stage_id,entry_id));
CREATE INDEX IF NOT EXISTS idx_vote_projects_public ON vote_projects(visibility,status,updated_at);
CREATE INDEX IF NOT EXISTS idx_vote_stages_project ON vote_stages(project_id,sort_order);
CREATE INDEX IF NOT EXISTS idx_vote_stage_entries_project ON vote_stage_entries(project_id,stage_id,status);
