-- Reference SQL for migration 0010; vnfest-migrate is authoritative.
CREATE TABLE IF NOT EXISTS vote_projects (id INT PRIMARY KEY AUTO_INCREMENT, project_type VARCHAR(20) NOT NULL, club_id INT NOT NULL, country VARCHAR(20) NOT NULL DEFAULT 'china', title VARCHAR(255) NOT NULL, year_label VARCHAR(20) NOT NULL DEFAULT '', description TEXT, cover_url VARCHAR(500) NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'draft', visibility VARCHAR(20) NOT NULL DEFAULT 'public', eligibility_mode VARCHAR(30) NOT NULL DEFAULT 'club_member', result_visibility VARCHAR(30) NOT NULL DEFAULT 'after_stage', config_json TEXT, share_token VARCHAR(40) NOT NULL DEFAULT '', guest_vote TINYINT NOT NULL DEFAULT 0, created_by INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, published_at DATETIME NULL, ended_at DATETIME NULL);
CREATE TABLE IF NOT EXISTS vote_stages (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, stage_key VARCHAR(40) NOT NULL, title VARCHAR(160) NOT NULL, sort_order INT NOT NULL DEFAULT 1, stage_type VARCHAR(30) NOT NULL, vote_mode VARCHAR(40) NOT NULL DEFAULT 'multi_select', max_select INT NOT NULL DEFAULT 1, advance_count INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'draft', starts_at DATETIME NULL, ends_at DATETIME NULL, config_json TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_stage (project_id,stage_key));
CREATE TABLE IF NOT EXISTS vote_entries (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, source_type VARCHAR(30) NOT NULL DEFAULT 'manual', source_id VARCHAR(191) NOT NULL DEFAULT '', identity_key VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, title_cn VARCHAR(255) NOT NULL DEFAULT '', subtitle VARCHAR(255) NOT NULL DEFAULT '', image_url VARCHAR(500) NOT NULL DEFAULT '', summary TEXT, external_url VARCHAR(500) NOT NULL DEFAULT '', entry_status VARCHAR(20) NOT NULL DEFAULT 'pending', submitted_by INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_entry_identity (project_id,identity_key));
CREATE TABLE IF NOT EXISTS vote_nominations (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, entry_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', note TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_nomination (project_id,entry_id,user_id));
CREATE TABLE IF NOT EXISTS vote_votes (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, stage_id INT NOT NULL, entry_id INT NOT NULL, user_id INT NULL, guest_key VARCHAR(64) NOT NULL DEFAULT '', score INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_ballot (stage_id,entry_id,user_id,guest_key));
CREATE TABLE IF NOT EXISTS vote_stage_entries (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, stage_id INT NOT NULL, entry_id INT NOT NULL, group_key VARCHAR(80) NOT NULL DEFAULT '', seed_no INT NOT NULL DEFAULT 0, source_stage_id INT NULL, source_result_rank INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_stage_entry (stage_id,entry_id));
CREATE TABLE IF NOT EXISTS vote_matches (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, stage_id INT NOT NULL, round_no INT NOT NULL DEFAULT 1, match_no INT NOT NULL DEFAULT 1, slot_a_entry_id INT NULL, slot_b_entry_id INT NULL, winner_entry_id INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', next_match_id INT NULL, next_slot VARCHAR(1) NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vote_results (id INT PRIMARY KEY AUTO_INCREMENT, project_id INT NOT NULL, stage_id INT NOT NULL, entry_id INT NOT NULL, rank_no INT NOT NULL DEFAULT 0, votes INT NOT NULL DEFAULT 0, score_avg DECIMAL(8,3) NULL, advanced TINYINT NOT NULL DEFAULT 0, snapshot_json TEXT, settled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_vote_result (stage_id,entry_id));
CREATE INDEX idx_vote_projects_public ON vote_projects(visibility,status,updated_at);
CREATE INDEX idx_vote_stages_project ON vote_stages(project_id,sort_order);
CREATE INDEX idx_vote_stage_entries_project ON vote_stage_entries(project_id,stage_id,status);
