-- Reference SQL for migration 0012; Go owns the complete schema and safe
-- add-missing-column repair for existing PHP installations.
CREATE TABLE IF NOT EXISTS galonly_events (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, location TEXT NOT NULL DEFAULT '', date TEXT NOT NULL, registration_open INTEGER NOT NULL DEFAULT 1, staff_only INTEGER NOT NULL DEFAULT 0, event_code TEXT NOT NULL DEFAULT '', description TEXT, staff_deadline TEXT, staff_max_applicants INTEGER, staff_required_count INTEGER NOT NULL DEFAULT 0, staff_registration_open INTEGER NOT NULL DEFAULT 1, staff_roster_finalized INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS galonly_applications (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER NOT NULL, event_number INTEGER, user_id INTEGER NOT NULL, is_joint INTEGER NOT NULL DEFAULT 0, joint_name TEXT NOT NULL DEFAULT '', wants_upgrade INTEGER NOT NULL DEFAULT 0, contact TEXT NOT NULL DEFAULT '', qq_number TEXT NOT NULL DEFAULT '', phone_number TEXT NOT NULL DEFAULT '', exhibition_experience TEXT NOT NULL DEFAULT '', notes TEXT, image_path TEXT NOT NULL DEFAULT '[]', display_image TEXT, booth_name TEXT NOT NULL DEFAULT '', booth_type TEXT NOT NULL DEFAULT '', expected_members INTEGER NOT NULL DEFAULT 0, layout_notes TEXT, needs_power TEXT NOT NULL DEFAULT 'unsure', attachment_paths TEXT NOT NULL DEFAULT '[]', merchandise_items TEXT NOT NULL DEFAULT '[]', merchandise_attachments TEXT NOT NULL DEFAULT '[]', merchandise_version INTEGER NOT NULL DEFAULT 0, merchandise_updated_at TEXT, phase2_approved_status TEXT, status TEXT NOT NULL DEFAULT 'pending', phase INTEGER NOT NULL DEFAULT 1, rejected_at TEXT, revision_at TEXT, resubmitted INTEGER NOT NULL DEFAULT 0, has_update INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS galonly_application_clubs (id INTEGER PRIMARY KEY AUTOINCREMENT, application_id INTEGER NOT NULL, club_id INTEGER NOT NULL, club_country TEXT NOT NULL DEFAULT '', UNIQUE(application_id,club_id));
CREATE TABLE IF NOT EXISTS galonly_votes (id INTEGER PRIMARY KEY AUTOINCREMENT, application_id INTEGER NOT NULL, auditer_id INTEGER NOT NULL, vote TEXT NOT NULL, comment TEXT, phase INTEGER NOT NULL DEFAULT 1, merchandise_version INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(application_id,auditer_id,phase,merchandise_version));
CREATE TABLE IF NOT EXISTS galonly_public_votes (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER NOT NULL, application_id INTEGER NOT NULL, ip_address TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,ip_address,application_id));
CREATE TABLE IF NOT EXISTS galonly_reviewers (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER NOT NULL DEFAULT 0, user_id INTEGER NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,user_id));
CREATE TABLE IF NOT EXISTS galonly_staff_applications (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER NOT NULL, user_id INTEGER NOT NULL, cn_name TEXT NOT NULL DEFAULT '', qq_number TEXT NOT NULL DEFAULT '', phone_number TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', club_id INTEGER NOT NULL DEFAULT 0, club_country TEXT NOT NULL DEFAULT 'china', positions TEXT NOT NULL DEFAULT '[]', confirm_schedule INTEGER NOT NULL DEFAULT 0, is_cosplay INTEGER NOT NULL DEFAULT 0, three_day_available INTEGER NOT NULL DEFAULT 0, self_intro TEXT, gender TEXT NOT NULL DEFAULT '', staff_experience INTEGER NOT NULL DEFAULT 0, skills TEXT, status TEXT NOT NULL DEFAULT 'pending', voted_by INTEGER, vote TEXT, resubmitted INTEGER NOT NULL DEFAULT 0, has_update INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
