-- Reference SQL for migration 0012; missing columns on pre-existing tables
-- are repaired additively by the Go migrator.
CREATE TABLE IF NOT EXISTS galonly_events (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL DEFAULT '', date DATE NOT NULL, registration_open TINYINT NOT NULL DEFAULT 1, staff_only TINYINT NOT NULL DEFAULT 0, event_code VARCHAR(32) NOT NULL DEFAULT '', description TEXT, staff_deadline DATETIME NULL, staff_max_applicants INT NULL, staff_required_count INT NOT NULL DEFAULT 0, staff_registration_open TINYINT NOT NULL DEFAULT 1, staff_roster_finalized TINYINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS galonly_applications (id INT PRIMARY KEY AUTO_INCREMENT, event_id INT NOT NULL, event_number INT NULL, user_id INT NOT NULL, is_joint TINYINT NOT NULL DEFAULT 0, joint_name VARCHAR(255) NOT NULL DEFAULT '', wants_upgrade TINYINT NOT NULL DEFAULT 0, contact VARCHAR(255) NOT NULL DEFAULT '', qq_number VARCHAR(32) NOT NULL DEFAULT '', phone_number VARCHAR(32) NOT NULL DEFAULT '', exhibition_experience TEXT, notes TEXT, image_path TEXT NOT NULL, display_image VARCHAR(500) NULL, booth_name VARCHAR(255) NOT NULL DEFAULT '', booth_type VARCHAR(30) NOT NULL DEFAULT '', expected_members INT NOT NULL DEFAULT 0, layout_notes TEXT, needs_power VARCHAR(20) NOT NULL DEFAULT 'unsure', attachment_paths TEXT, merchandise_items TEXT, merchandise_attachments TEXT, merchandise_version INT NOT NULL DEFAULT 0, merchandise_updated_at DATETIME NULL, phase2_approved_status VARCHAR(30) NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', phase INT NOT NULL DEFAULT 1, rejected_at DATETIME NULL, revision_at DATETIME NULL, resubmitted TINYINT NOT NULL DEFAULT 0, has_update TINYINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS galonly_application_clubs (id INT PRIMARY KEY AUTO_INCREMENT, application_id INT NOT NULL, club_id INT NOT NULL, club_country VARCHAR(50) NOT NULL DEFAULT '', UNIQUE KEY uq_galonly_application_club (application_id,club_id));
CREATE TABLE IF NOT EXISTS galonly_votes (id INT PRIMARY KEY AUTO_INCREMENT, application_id INT NOT NULL, auditer_id INT NOT NULL, vote VARCHAR(10) NOT NULL, comment TEXT NULL, phase INT NOT NULL DEFAULT 1, merchandise_version INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_galonly_vote (application_id,auditer_id,phase,merchandise_version));
CREATE TABLE IF NOT EXISTS galonly_public_votes (id INT PRIMARY KEY AUTO_INCREMENT, event_id INT NOT NULL, application_id INT NOT NULL, ip_address VARCHAR(45) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_galonly_public_vote (event_id,ip_address,application_id));
CREATE TABLE IF NOT EXISTS galonly_reviewers (id INT PRIMARY KEY AUTO_INCREMENT, event_id INT NOT NULL DEFAULT 0, user_id INT NOT NULL, role VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_galonly_reviewer (event_id,user_id));
CREATE TABLE IF NOT EXISTS galonly_staff_applications (id INT PRIMARY KEY AUTO_INCREMENT, event_id INT NOT NULL, user_id INT NOT NULL, cn_name VARCHAR(255) NOT NULL DEFAULT '', qq_number VARCHAR(32) NOT NULL DEFAULT '', phone_number VARCHAR(32) NOT NULL DEFAULT '', email VARCHAR(255) NOT NULL DEFAULT '', club_id INT NOT NULL DEFAULT 0, club_country VARCHAR(50) NOT NULL DEFAULT 'china', positions TEXT, confirm_schedule TINYINT NOT NULL DEFAULT 0, is_cosplay TINYINT NOT NULL DEFAULT 0, three_day_available TINYINT NOT NULL DEFAULT 0, self_intro TEXT, gender VARCHAR(20) NOT NULL DEFAULT '', staff_experience TINYINT NOT NULL DEFAULT 0, skills TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', voted_by INT NULL, vote VARCHAR(20) NULL, resubmitted TINYINT NOT NULL DEFAULT 0, has_update TINYINT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
